name: CI Pipeline
on:  # yamllint disable-line rule:truthy
  push:
    branches: [master]
  pull_request:
jobs:
  test:
    runs-on: ${% raw %}{{ matrix.os }}{% endraw %}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${% raw %}{{ matrix.python-version }}{% endraw %}.
        uses: actions/setup-python@v2
        with:
          python-version: ${% raw %}{{ matrix.python-version }}{% endraw %}

      - name: Install dependencies.
        run: |
          python -m pip install -U pip tox

      - name: Unit tests
        run: |
          make test
