name: CI Pipeline
on:  # yamllint disable-line rule:truthy
  push:
    branches: [master]
  pull_request:
jobs:
  test:
    runs-on: ${% raw %}{{ matrix.os }}{% endraw %}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${% raw %}{{ matrix.python-version }}{% endraw %}.
        uses: actions/setup-python@v2
        with:
          python-version: ${% raw %}{{ matrix.python-version }}{% endraw %}

      - name: Install dependencies.
        run: |
          python -m pip install -U pip tox

      - name: Unit tests
        run: |
          make test

      - name: Publish coverage to codecov.io.
        if: matrix.python-version == '3.9' && ! env.ACT
        run: |
          python -m pip install -U coverage
          bash <(curl -s https://codecov.io/bash) -cF python
  lint:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Run linters.
        run: |
          make lint

  publish:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install pypa/build
        run: |
          python -m pip install --user build

      - name: Build a binary wheel and a source tarball
        run: |
          python -m build --sdist --wheel --outdir dist/

      - name: Build wheels
        run: |
          python setup.py sdist

      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true

      - name: Publish distribution to PyPI
        if: github.repository == 'bbugyi200/{{ cookiecutter.git_repo_name }}' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
