---
version: '3.7'
services:
  {{ cookiecutter.package_name }}:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/{{ cookiecutter.package_path }}:delegated
      - build:/{{ cookiecutter.package_path }}/build
      - venv:/{{ cookiecutter.package_path }}/.venv
      - docker-python-cache:/root/.cache/
    working_dir: /{{ cookiecutter.package_path }}
    environment:
      - BETTER_EXCEPTIONS
      - CC_REPO_URL
volumes:
  docker-python-cache:
    external: true
  build:
  venv:
