---
version: '3.7'
services:
  {{ cookiecutter.package_name }}:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/{{ cookiecutter.package_path }}:delegated
    working_dir: /{{ cookiecutter.package_path }}
    environment:
      - BETTER_EXCEPTIONS
      - CC_REPO_URL
